### ISSUE TITLE
0.0.6？

### ISSUE THREAD

**Issue by mcrpanda** [A-da-m/AppleMusicPresence#1]
Hi,

It seems that 0.0.6 is the latest version? but I can only download the 0.0.5.

After clicking the app, the window will disappear, but I can track the processes in the activity monitor.

In Discord, I can see "playing apple music", but no song information, only says "browsing".

**Comment by A-da-m** [comment]
It is due to a recent change that requires all developers to notarize they’re apps. Current I am working in getting a electron patch that allows me to do that but until that’s completed you can only run the app by cloning the repo, install node, then running yarn dev.

**Comment by ghost** [comment]
@A-da-m Until then, can you post a guide to running it straight from the cloned repo?

**Comment by A-da-m** [comment]
@idealleee @mattgeowild I believe I finally figured out the issue after hours of debugging and searching google. 0.0.6 has been released with notarization support https://github.com/A-da-m/AppleMusicPresence/releases/tag/0.0.6.
