### ISSUE TITLE
Doesn't work on macOS Big Sur (11.0)

### ISSUE THREAD

**Issue by A-da-m** [A-da-m/AppleMusicPresence#7]
The app launches but never connects to discord or just disappears from the Menu Bar.

**Comment by joel-tonuri** [comment]
Same issue here. Doesn't work on the public release version of Big Sur (11.0.1) either unfortunately.

**Comment by A-da-m** [comment]
@joel-tonuri The issue appears to be related to AppleScript. Apple must have broken it or changed how it functions breaking most apps that fetch music using AppleScript. I’m looking into another solution that would work but would require a rewrite in Swift. I’ll keep you updated on any progress here.

**Comment by A-da-m** [comment]
@joel-tonuri After a few hours of work, I figured out a new solution. It's not perfect but it is a lot better then not having AppleScript work. You can download the beta version at https://github.com/A-da-m/AppleMusicPresence/releases/tag/1.0.0-dev. This version is macOS 11 only, previous versions can use the 0.0.7 for AMP.

**Comment by joel-tonuri** [comment]
> @joel-tonuri After a few hours of work, I figured out a new solution. It's not perfect but it is a lot better then not having AppleScript work. You can download the beta version at https://github.com/A-da-m/AppleMusicPresence/releases/tag/1.0.0-dev. This version is macOS 11 only, previous versions can use the 0.0.7 for AMP.

Thanks heaps! I've been using it for the past few days -- really solid -- I appreciate you taking the time to update this project. I'll let you know if I run into any unexpected issues.
