### ISSUE TITLE
Doesn’t appear in status bar

### ISSUE THREAD

**Issue by xrisk** [A-da-m/AppleMusicPresence#8]
I think the app is supposed to be controllable via the status bar. I don’t get anything there on Catalina.

**Comment by A-da-m** [comment]
Yeah, I'm having the same issue on Big Sur. For me it looks like AppleScript is just broken in Big Sur so I can't recreate. I'll test in Catalina later next week.

**Comment by xrisk** [comment]
This is the problem I think: https://www.electronjs.org/docs/faq#my-apps-tray-disappeared-after-a-few-minutes 

I changed it on my fork and the problem was gone.

**Comment by A-da-m** [comment]
Yep I saw. I'll merge the PR but I won't be able to build the app until I resolve the AppleScript issue.
